import { motion } from 'framer-motion';
import { CalendarClock, CheckCircle2, Factory, Wrench } from 'lucide-react';
import { useListEquipment } from '@workspace/api-client-react';
import type { EquipmentItem } from '@workspace/api-client-react';
import { fallbackEquipment } from '../lib/bakery-data';

export function EquipmentPage() {
  const equipmentQuery = useListEquipment();
  const equipment: EquipmentItem[] = equipmentQuery.data ?? fallbackEquipment;
  return <main className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-12 lg:py-14">
    <div className="flex flex-col justify-between gap-6 border-b border-border pb-8 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 font-mono-ui text-[10px] uppercase tracking-[.2em] text-primary"><Factory size={13} /> Studio care</div><h1 className="font-display text-5xl tracking-[-.05em]">Equipment</h1><p className="mt-3 text-sm text-muted-foreground">A good bake starts with equipment you trust.</p></div><div className="flex items-center gap-2 rounded-full bg-primary/10 px-3 py-2 text-xs text-primary"><CheckCircle2 size={14} /> {equipment.filter((item) => item.status === 'operational').length} operational</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{equipment.map((item, index) => { const due = item.status.toLowerCase().includes('due'); return <motion.article initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }} key={item.id} className={`border bg-card p-6 ${due ? 'border-accent' : 'border-border'}`} data-testid={`card-equipment-${item.id}`}><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-full ${due ? 'bg-accent/20 text-accent-foreground' : 'bg-secondary text-primary'}`}><Wrench size={18} strokeWidth={1.6} /></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.08em] ${due ? 'bg-accent/25 text-accent-foreground' : 'bg-primary/10 text-primary'}`}>{item.status}</span></div><h2 className="mt-7 font-display text-2xl">{item.name}</h2><p className="mt-1 text-xs text-muted-foreground">{item.category}</p><div className="mt-8 flex items-center justify-between border-t border-border pt-4 text-xs"><span className="flex items-center gap-2 text-muted-foreground"><CalendarClock size={14} /> Next service</span><span className={due ? 'font-semibold text-accent-foreground' : ''}>{new Date(item.nextService).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</span></div>{due && <button onClick={() => window.alert(`Service request noted for ${item.name}.`)} className="mt-5 w-full rounded-md border border-accent py-2 text-xs font-semibold text-accent-foreground hover:bg-accent/10" data-testid={`button-schedule-service-${item.id}`}>Schedule service</button>}</motion.article>; })}</div>
  </main>;
}