import { motion } from 'framer-motion';
import { Boxes, Check, Plus, Search, X } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useCreateInventory, useListInventory } from '@workspace/api-client-react';
import type { InventoryInput, InventoryItem } from '@workspace/api-client-react';
import { fallbackInventory, money } from '../lib/bakery-data';

const blankForm: InventoryInput = { name: '', category: 'Dry goods', unit: 'kg', quantity: 0, reorderAt: 1, cost: 0 };

export function InventoryPage() {
  const inventoryQuery = useListInventory();
  const createInventory = useCreateInventory();
  const [items, setItems] = useState<InventoryItem[]>(fallbackInventory);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All');
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState<InventoryInput>(blankForm);
  const liveItems = inventoryQuery.data ?? items;
  const filtered = useMemo(() => liveItems.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (filter === 'All' || item.status === filter.toLowerCase())), [filter, liveItems, search]);
  const save = (event: FormEvent) => {
    event.preventDefault();
    const localItem: InventoryItem = { ...form, id: Date.now(), status: form.quantity <= form.reorderAt ? 'low' : 'healthy' };
    setItems((current) => [localItem, ...current]);
    createInventory.mutate({ data: form }, { onSuccess: () => inventoryQuery.refetch() });
    setForm(blankForm);
    setShowForm(false);
  };
  return <main className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-12 lg:py-14">
    <div className="flex flex-col justify-between gap-6 border-b border-border pb-8 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 font-mono-ui text-[10px] uppercase tracking-[.2em] text-primary"><Boxes size={13} /> Pantry ledger</div><h1 className="font-display text-5xl tracking-[-.05em]">Inventory</h1><p className="mt-3 text-sm text-muted-foreground">Know what’s on the shelf before the first whisk.</p></div><button onClick={() => setShowForm(true)} className="flex w-fit items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm text-primary-foreground" data-testid="button-add-inventory"><Plus size={16} /> Add ingredient</button></div>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search ingredients" className="h-11 w-full rounded-lg border border-border bg-card pl-10 pr-3 text-sm outline-none focus:border-primary" data-testid="input-search-inventory" /></div><div className="flex items-center gap-2"><span className="font-mono-ui text-[10px] uppercase tracking-[.1em] text-muted-foreground">Show</span>{['All', 'Low', 'Critical'].map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-2 text-xs ${filter === value ? 'bg-foreground text-background' : 'border border-border text-muted-foreground'}`} data-testid={`button-filter-${value.toLowerCase()}`}>{value}</button>)}</div></div>
    <div className="mt-7 overflow-x-auto border border-border bg-card"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-border bg-muted/50"><tr className="font-mono-ui text-[10px] uppercase tracking-[.1em] text-muted-foreground"><th className="px-5 py-4">Ingredient</th><th className="px-5 py-4">Category</th><th className="px-5 py-4">On hand</th><th className="px-5 py-4">Reorder at</th><th className="px-5 py-4">Unit cost</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{filtered.map((item, index) => <motion.tr initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: index * .035 }} key={item.id} className="border-b border-border last:border-0 hover:bg-muted/30" data-testid={`row-inventory-${item.id}`}><td className="px-5 py-4 text-sm font-semibold">{item.name}</td><td className="px-5 py-4 text-sm text-muted-foreground">{item.category}</td><td className="px-5 py-4 font-mono-ui text-xs">{item.quantity} {item.unit}</td><td className="px-5 py-4 font-mono-ui text-xs text-muted-foreground">{item.reorderAt} {item.unit}</td><td className="px-5 py-4 font-mono-ui text-xs">{money(item.cost)}</td><td className="px-5 py-4"><StatusPill status={item.status} /></td></motion.tr>)}</tbody></table>{filtered.length === 0 && <div className="p-14 text-center"><p className="font-display text-2xl">Nothing on that shelf.</p><p className="mt-2 text-sm text-muted-foreground">Try another ingredient or category.</p></div>}</div>
    <div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span data-testid="text-inventory-count">{filtered.length} of {liveItems.length} ingredients</span><span>Last synced just now</span></div>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/20 p-5" role="dialog"><motion.form initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} onSubmit={save} className="w-full max-w-lg border border-border bg-card p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.15em] text-primary">New line item</p><h2 className="mt-2 font-display text-3xl">Add to the pantry</h2></div><button type="button" onClick={() => setShowForm(false)} className="text-muted-foreground" aria-label="Close form" data-testid="button-close-inventory-form"><X size={18} /></button></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Ingredient name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} required /><Field label="Category" value={form.category} onChange={(value) => setForm({ ...form, category: value })} /><Field label="Unit" value={form.unit} onChange={(value) => setForm({ ...form, unit: value })} /><NumberField label="Quantity" value={form.quantity} onChange={(value) => setForm({ ...form, quantity: value })} /><NumberField label="Reorder at" value={form.reorderAt} onChange={(value) => setForm({ ...form, reorderAt: value })} /><NumberField label="Unit cost (GHS)" value={form.cost} onChange={(value) => setForm({ ...form, cost: value })} /></div><button disabled={createInventory.isPending} className="mt-7 flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-3 text-sm font-semibold text-primary-foreground disabled:opacity-60" data-testid="button-save-inventory">{createInventory.isPending ? 'Saving…' : <><Check size={16} /> Save ingredient</>}</button></motion.form></div>}
  </main>;
}

function StatusPill({ status }: { status: string }) { const critical = status === 'critical'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.08em] ${critical ? 'bg-destructive/10 text-destructive' : status === 'low' ? 'bg-accent/25 text-accent-foreground' : 'bg-primary/10 text-primary'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>; }
function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="text-xs font-semibold">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-border bg-background px-3 text-sm font-normal outline-none focus:border-primary" data-testid={`input-${label.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-')}`} /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs font-semibold">{label}<input type="number" min="0" step="0.1" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 h-10 w-full rounded-md border border-border bg-background px-3 text-sm font-normal outline-none focus:border-primary" data-testid={`input-${label.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-')}`} /></label>; }